version: "3.5"
services:
  shop-online-app:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres:12.1
    container_name: shop_postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "banan123"
      POSTGRES_DB: "db"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: