logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/db"
    username: "user"
    password: "banan123"

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true

app:
  db-init: true
  jwt:
    secret: "U29tZVNlY3JldEtleVRvR2VuZXJhdGVKV1Rz"
    tokenValidityMilis: 86400000 # 86400000ms = 24h